### ISSUE TITLE
Any options for the retry?

### ISSUE THREAD

**Issue by vovkanaz** [cloudflare/origin-ca-issuer#115]
Does [origin-ca-issuer](https://github.com/cloudflare/origin-ca-issuer) support any option for the retry to be able to prevent some errors e.g.
```
Failed to sign certificate request: unable to sign request: Cloudflare API Error code=1100 message=Failed to write certificate to Database
```
Is there a way to do this automatically?

**Comment by terinjokes** [comment]
The controller does retry reconcilation of CertificateRequests for internal errors.

However, errors from API related to signing certificates cause this controller to update the status condition of the CertificateRequest (Ready=False, Reason=Failed), a defined condition for [CertificateRequest](https://cert-manager.io/docs/usage/certificaterequest/#ready) resources. The expectation is that cert-manager would create a new CertificateRequest to renew the certificate, which origin-ca-issuer would pickup and handle.

**Comment by rayterrill** [comment]
We just got hit with the same issue, and cert manager seemingly did not create a new request because the previous one was errored. This caused an outage as the cert expired and was not renewed correctly.

We removed the outstanding request and deleted the certificate resource to get things renewed quickly once discovered.
