### ISSUE TITLE
Full Strict SSL - ca.crt available for ingress

### ISSUE THREAD

**Issue by mhaddon** [cloudflare/origin-ca-issuer#25]
I have the OriginIssuer working and integrated with Istio. 
OriginIssuer and cert-manager create a certificate with "tls.crt" and "tls.key", then an Istio Gateway resource uses those credentials to provide a certificate for the server.

The problem is, I want to use Full Strict SSL, which I believe means I need to set my Istio Gateway to Mutual TLS mode. However, I believe in order to achieve this I need the "ca.crt" available inside of the certificate secret. Which is currently not the case.

Is there a way to embed this information into the secret? It seems if you use cert-manager with your own provided CA it embeds it for you, so presumably there is the functionality.

docs: https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-mutual-tls-ingress-gateway 

[edit] I realise I have probably gotten confused between Full Strict SSL and https://developers.cloudflare.com/access/service-auth/mtls, can someone confirm if this is the case? Also, would the same answer be possible for this other feature?

**Comment by terinjokes** [comment]
Full Strict SSL is a separate feature from mTLS:

- Full Strict SSL is a configuration where Cloudflare connects to your server with TLS and requires a valid certificate for the domain to be presented. This can either be a valid certificate from a well known CA, or a certificate issued by the Origin CA feature. This is in comparison to other modes where Cloudflare will accept a self-signed certificate, or downgrade requests to you server to HTTP.
- mTLS is a feature where Cloudflare will present a client certificate to your server, so your server can verify the connection came from Cloudflare.

This issuer only handles the first use case, if we were to set the "ca.crt" field, it would be the Origin CA's certificate. Cloudflare uses different CAs for mTLS and Origin CA.

Istio supports loading loading the CA certificate from a separate secret in some situations, but it does not look to support it in the case you're using TLS-style secrets.

> * A generic Secret with keys `key` and `cert`. For mutual TLS, a separate generic Secret named `<secret>-cacert`, with a `cacert` key.

Supporting a separate CA certificate when using TLS-style certificates should probably be a feature request in Istio.

/cc @munnerz

**Comment by terinjokes** [comment]
@mhaddon If you do decide to open an Istio feature request, do let me know.

**Comment by dm3ch** [comment]
I have faced issue as described here. I fully understand previous answer but still have some questions.

It typically not so easy to get something changed in istio contract.

@terinjokes Why adding some configuration field to Issuer switching `ca.crt` behaviour between Origin CA and mTLS Origin CA (having Origin CA default option) is not considered?

**Comment by terinjokes** [comment]
That CA is for an entirely different feature that has little to do with getting a certificate issued and signed.

I would imagine the IaaC configuring Cloudflare would also populate the mTLS CA used as a [ClusterTrustBundle](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#ctb-signer-unlinked) and configure Istio to use it to verify the peer.

**Comment by dm3ch** [comment]
Thank you for answer.

The issue is it seems right now there're no existing solutions to automate origin-ca and mTLS usage at same time with istio.

What you proposes wouldn't work as far as I understand, cause istio validates incoming connection not using a trust bundle it have in pod or somewhere else, but with CA from the secret it receives in credentials secret.

So I see 4 ways to fix this:
- Make istio retrieve ca separately. I would open a feature request, but istio very rarely changes it contracts. :(
- Make cert-manager support writing not only kubernetes.io/tls certs - https://github.com/cert-manager/cert-manager/issues/7588 but there're also a lot of friction here, cause it seems not so many usecases when tls secret type can't be used.
- Modifying cert after issue, but so far I haven't found operators able to transform secrets.
- Make origin-ca-issuer able to produce cert with another CA.

So far adjusting this issuer behaviour seems (for me) the good balance between simple and right solution.

Why having a separate configuration field or presenting new `requestType` (indicating that it have mTLS CA) can't be an option? From my point of view it would allow to just cover additional use cases, without braking any compatibility with currently supported usecases.

Am I missing something?

**Comment by terinjokes** [comment]
The "ca.crt" field is intended to be the CA (or intermediate) that signed the certificate presented in "tls.crt". Setting some other CA there would break the meaning of the field. It is not uncommon (and required in the case of Origin CA Issuer) that the peer's CA is going to be different than the local certificate's CA.

The Istio documentation linked in the OP makes it sound like using a separate certificate is already a supported feature:

> For mutual TLS, a separate generic Secret named `<secret>-cacert`, with a `cacert` key.

**Comment by dm3ch** [comment]
While https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#key-formats doesn't explicitly says that `-cacert` secret can be used in combination with `kubernetes.io/tls` secret after quick test I find out that it seems to work.

Thank you for highlighting that

**Comment by terinjokes** [comment]
I'm glad that works.

It might prove helpful to others if a PR is opened to add it as a bullet point to those docs and this status update added to your comment in https://github.com/cert-manager/cert-manager/issues/7588?

**Comment by dm3ch** [comment]
> I'm glad that works.
> 
> It might prove helpful to others if a PR is opened to add it as a bullet point to those docs and this status update added to your comment in [cert-manager/cert-manager#7588](https://github.com/cert-manager/cert-manager/issues/7588)?

Working on that
